### ISSUE TITLE
Adding custom fields to Taxonomy

### ISSUE THREAD

**Issue by RonnieTaz** [vanilophp/category#5]
Is it possible to add extra fields to Taxonomy apart from its two main fields? I have an app that needs to have categories with images. I want to add some fields in the taxonomy to hold the URL of the image and another field to mark the taxonomy name as it comes from another server. Is this possible?

**Comment by fulopattila122** [comment]
Yes, it is. Before we continue, one question: are you using the entire Vanilo framework or just the standalone category module?

**Comment by fulopattila122** [comment]
I am asking because assigning images to taxons/taxonomies in the framework is possible.

## Assign Images

The framework extends the base models with image capabilities, using (by default) the [Spatie Media Library](https://spatie.be/docs/laravel-medialibrary/v10/introduction)

![image](https://user-images.githubusercontent.com/1162360/169840948-9c625142-fd32-41ac-85f6-944bcf148641.png)

If this solution doesn't work for you, please let me know, there are alternatives.

## Adding New Fields

Adding new fields to a model is also possible, described step by step here: https://vanilo.io/how-to/use-custom-models-in-your-application

**Comment by RonnieTaz** [comment]
> Yes, it is. Before we continue, one question: are you using the entire Vanilo framework or just the standalone category module?

The standalone category module and some other modules.

> Adding new fields to a model is also possible, described step by step here: [https://vanilo.io/how-to/use-custom-models-in-your-application](https://vanilo.io/how-to/use-custom-models-in-your-application)

I think I will take this approach. Much thanks.
