### ISSUE TITLE
Retrieving all Models with associated taxon

### ISSUE THREAD

**Issue by chellmann** [vanilophp/category#6]
Hello,

let's assume we have more then one Model for Products in Categories.
How would it possible to get ALL Models associated with a Taxon?

Thanks a lot!

**Comment by fulopattila122** [comment]
More than one model of the same class (eg. `Product`), or more than one type of model class (eg. `Product` and `Subscription`)?

**Comment by chellmann** [comment]
More than one type of Model.

**Comment by fulopattila122** [comment]
I assume you only receive one type of model, but you need all of them.
How do you currently return the models from a category (taxon)?

**Comment by chellmann** [comment]
Yes, only one type of model because the only way i found in the documentation would be $taxon->type_of_model
As in the Laravel Docs (https://laravel.com/docs/9.x/eloquent-relationships#querying-morph-to-relationships) described there is a way with **whereHasMorph** but i would like to query ALL associated Models, without having to specify them.

**Comment by fulopattila122** [comment]
I set up a small project to test it, but I don't know how to do that with Laravel TBH without explicitly telling the types to Laravel.
Maybe at Laravel discussions there's a solution for that.

Since the question is not Vanilo specific, I'm closing it for now, but I'd be happy if you could share the solution here if you find it. :bow:
